image: gitpod/workspace-python-3.9

ports:
  - name: FastAPI
    port: 8000
    onOpen: open-browser
    visibility: public
  - name: Streamlit
    port: 8501
    onOpen: open-browser
    visibility: public

tasks:
  - name: Instalar dependencias y ejecutar aplicación
    init: |
      pip install -r requirements.txt
    command: |
      pip install -r requirements.txt
      chmod +x start.sh
      ./start.sh

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
